#include "pitchy/midi/midi_note.h"

#include <catch2/catch_test_macros.hpp>

using namespace pitchy;

TEST_CASE("NoteToMidiValue", "midi_note_test")
{
  REQUIRE(21 == note_to_midi_value(midi_note::A0));
  REQUIRE(22 == note_to_midi_value(midi_note::As0));
  REQUIRE(23 == note_to_midi_value(midi_note::B0));
  REQUIRE(24 == note_to_midi_value(midi_note::C1));
  REQUIRE(25 == note_to_midi_value(midi_note::Cs1));
  REQUIRE(26 == note_to_midi_value(midi_note::D1));
  REQUIRE(27 == note_to_midi_value(midi_note::Ds1));
  REQUIRE(28 == note_to_midi_value(midi_note::E1));
  REQUIRE(29 == note_to_midi_value(midi_note::F1));
  REQUIRE(30 == note_to_midi_value(midi_note::Fs1));
  REQUIRE(31 == note_to_midi_value(midi_note::G1));
  REQUIRE(32 == note_to_midi_value(midi_note::Gs1));
  REQUIRE(33 == note_to_midi_value(midi_note::A1));
  REQUIRE(34 == note_to_midi_value(midi_note::As1));
  REQUIRE(35 == note_to_midi_value(midi_note::B1));
  REQUIRE(36 == note_to_midi_value(midi_note::C2));
  REQUIRE(37 == note_to_midi_value(midi_note::Cs2));
  REQUIRE(38 == note_to_midi_value(midi_note::D2));
  REQUIRE(39 == note_to_midi_value(midi_note::Ds2));
  REQUIRE(40 == note_to_midi_value(midi_note::E2));
  REQUIRE(41 == note_to_midi_value(midi_note::F2));
  REQUIRE(42 == note_to_midi_value(midi_note::Fs2));
  REQUIRE(43 == note_to_midi_value(midi_note::G2));
  REQUIRE(44 == note_to_midi_value(midi_note::Gs2));
  REQUIRE(45 == note_to_midi_value(midi_note::A2));
  REQUIRE(46 == note_to_midi_value(midi_note::As2));
  REQUIRE(47 == note_to_midi_value(midi_note::B2));
  REQUIRE(48 == note_to_midi_value(midi_note::C3));
  REQUIRE(49 == note_to_midi_value(midi_note::Cs3));
  REQUIRE(50 == note_to_midi_value(midi_note::D3));
  REQUIRE(51 == note_to_midi_value(midi_note::Ds3));
  REQUIRE(52 == note_to_midi_value(midi_note::E3));
  REQUIRE(53 == note_to_midi_value(midi_note::F3));
  REQUIRE(54 == note_to_midi_value(midi_note::Fs3));
  REQUIRE(55 == note_to_midi_value(midi_note::G3));
  REQUIRE(56 == note_to_midi_value(midi_note::Gs3));
  REQUIRE(57 == note_to_midi_value(midi_note::A3));
  REQUIRE(58 == note_to_midi_value(midi_note::As3));
  REQUIRE(59 == note_to_midi_value(midi_note::B3));
  REQUIRE(60 == note_to_midi_value(midi_note::C4));
  REQUIRE(61 == note_to_midi_value(midi_note::Cs4));
  REQUIRE(62 == note_to_midi_value(midi_note::D4));
  REQUIRE(63 == note_to_midi_value(midi_note::Ds4));
  REQUIRE(64 == note_to_midi_value(midi_note::E4));
  REQUIRE(65 == note_to_midi_value(midi_note::F4));
  REQUIRE(66 == note_to_midi_value(midi_note::Fs4));
  REQUIRE(67 == note_to_midi_value(midi_note::G4));
  REQUIRE(68 == note_to_midi_value(midi_note::Gs4));
  REQUIRE(69 == note_to_midi_value(midi_note::A4));
  REQUIRE(70 == note_to_midi_value(midi_note::As4));
  REQUIRE(71 == note_to_midi_value(midi_note::B4));
  REQUIRE(72 == note_to_midi_value(midi_note::C5));
  REQUIRE(73 == note_to_midi_value(midi_note::Cs5));
  REQUIRE(74 == note_to_midi_value(midi_note::D5));
  REQUIRE(75 == note_to_midi_value(midi_note::Ds5));
  REQUIRE(76 == note_to_midi_value(midi_note::E5));
  REQUIRE(77 == note_to_midi_value(midi_note::F5));
  REQUIRE(78 == note_to_midi_value(midi_note::Fs5));
  REQUIRE(79 == note_to_midi_value(midi_note::G5));
  REQUIRE(80 == note_to_midi_value(midi_note::Gs5));
  REQUIRE(81 == note_to_midi_value(midi_note::A5));
  REQUIRE(82 == note_to_midi_value(midi_note::As5));
  REQUIRE(83 == note_to_midi_value(midi_note::B5));
  REQUIRE(84 == note_to_midi_value(midi_note::C6));
  REQUIRE(85 == note_to_midi_value(midi_note::Cs6));
  REQUIRE(86 == note_to_midi_value(midi_note::D6));
  REQUIRE(87 == note_to_midi_value(midi_note::Ds6));
  REQUIRE(88 == note_to_midi_value(midi_note::E6));
  REQUIRE(89 == note_to_midi_value(midi_note::F6));
  REQUIRE(90 == note_to_midi_value(midi_note::Fs6));
  REQUIRE(91 == note_to_midi_value(midi_note::G6));
  REQUIRE(92 == note_to_midi_value(midi_note::Gs6));
  REQUIRE(93 == note_to_midi_value(midi_note::A6));
  REQUIRE(94 == note_to_midi_value(midi_note::As6));
  REQUIRE(95 == note_to_midi_value(midi_note::B6));
  REQUIRE(96 == note_to_midi_value(midi_note::C7));
  REQUIRE(97 == note_to_midi_value(midi_note::Cs7));
  REQUIRE(98 == note_to_midi_value(midi_note::D7));
  REQUIRE(99 == note_to_midi_value(midi_note::Ds7));
  REQUIRE(100 == note_to_midi_value(midi_note::E7));
  REQUIRE(101 == note_to_midi_value(midi_note::F7));
  REQUIRE(102 == note_to_midi_value(midi_note::Fs7));
  REQUIRE(103 == note_to_midi_value(midi_note::G7));
  REQUIRE(104 == note_to_midi_value(midi_note::Gs7));
  REQUIRE(105 == note_to_midi_value(midi_note::A7));
  REQUIRE(106 == note_to_midi_value(midi_note::As7));
  REQUIRE(107 == note_to_midi_value(midi_note::B7));
  REQUIRE(108 == note_to_midi_value(midi_note::C8));
  REQUIRE(109 == note_to_midi_value(midi_note::Cs8));
  REQUIRE(110 == note_to_midi_value(midi_note::D8));
  REQUIRE(111 == note_to_midi_value(midi_note::Ds8));
  REQUIRE(112 == note_to_midi_value(midi_note::E8));
  REQUIRE(113 == note_to_midi_value(midi_note::F8));
  REQUIRE(114 == note_to_midi_value(midi_note::Fs8));
  REQUIRE(115 == note_to_midi_value(midi_note::G8));
  REQUIRE(116 == note_to_midi_value(midi_note::Gs8));
  REQUIRE(117 == note_to_midi_value(midi_note::A8));
  REQUIRE(118 == note_to_midi_value(midi_note::As8));
  REQUIRE(119 == note_to_midi_value(midi_note::B8));
  REQUIRE(120 == note_to_midi_value(midi_note::C9));
  REQUIRE(121 == note_to_midi_value(midi_note::Cs9));
  REQUIRE(122 == note_to_midi_value(midi_note::D9));
  REQUIRE(123 == note_to_midi_value(midi_note::Ds9));
  REQUIRE(124 == note_to_midi_value(midi_note::E9));
  REQUIRE(125 == note_to_midi_value(midi_note::F9));
  REQUIRE(126 == note_to_midi_value(midi_note::Fs9));
  REQUIRE(127 == note_to_midi_value(midi_note::G9));
}

TEST_CASE("MidiValueToNote", "midi_note_test")
{
  REQUIRE(midi_value_to_note(21) == midi_note::A0);
  REQUIRE(midi_value_to_note(22) == midi_note::As0);
  REQUIRE(midi_value_to_note(23) == midi_note::B0);
  REQUIRE(midi_value_to_note(24) == midi_note::C1);
  REQUIRE(midi_value_to_note(25) == midi_note::Cs1);
  REQUIRE(midi_value_to_note(26) == midi_note::D1);
  REQUIRE(midi_value_to_note(27) == midi_note::Ds1);
  REQUIRE(midi_value_to_note(28) == midi_note::E1);
  REQUIRE(midi_value_to_note(29) == midi_note::F1);
  REQUIRE(midi_value_to_note(30) == midi_note::Fs1);
  REQUIRE(midi_value_to_note(31) == midi_note::G1);
  REQUIRE(midi_value_to_note(32) == midi_note::Gs1);
  REQUIRE(midi_value_to_note(33) == midi_note::A1);
  REQUIRE(midi_value_to_note(34) == midi_note::As1);
  REQUIRE(midi_value_to_note(35) == midi_note::B1);
  REQUIRE(midi_value_to_note(36) == midi_note::C2);
  REQUIRE(midi_value_to_note(37) == midi_note::Cs2);
  REQUIRE(midi_value_to_note(38) == midi_note::D2);
  REQUIRE(midi_value_to_note(39) == midi_note::Ds2);
  REQUIRE(midi_value_to_note(40) == midi_note::E2);
  REQUIRE(midi_value_to_note(41) == midi_note::F2);
  REQUIRE(midi_value_to_note(42) == midi_note::Fs2);
  REQUIRE(midi_value_to_note(43) == midi_note::G2);
  REQUIRE(midi_value_to_note(44) == midi_note::Gs2);
  REQUIRE(midi_value_to_note(45) == midi_note::A2);
  REQUIRE(midi_value_to_note(46) == midi_note::As2);
  REQUIRE(midi_value_to_note(47) == midi_note::B2);
  REQUIRE(midi_value_to_note(48) == midi_note::C3);
  REQUIRE(midi_value_to_note(49) == midi_note::Cs3);
  REQUIRE(midi_value_to_note(50) == midi_note::D3);
  REQUIRE(midi_value_to_note(51) == midi_note::Ds3);
  REQUIRE(midi_value_to_note(52) == midi_note::E3);
  REQUIRE(midi_value_to_note(53) == midi_note::F3);
  REQUIRE(midi_value_to_note(54) == midi_note::Fs3);
  REQUIRE(midi_value_to_note(55) == midi_note::G3);
  REQUIRE(midi_value_to_note(56) == midi_note::Gs3);
  REQUIRE(midi_value_to_note(57) == midi_note::A3);
  REQUIRE(midi_value_to_note(58) == midi_note::As3);
  REQUIRE(midi_value_to_note(59) == midi_note::B3);
  REQUIRE(midi_value_to_note(60) == midi_note::C4);
  REQUIRE(midi_value_to_note(61) == midi_note::Cs4);
  REQUIRE(midi_value_to_note(62) == midi_note::D4);
  REQUIRE(midi_value_to_note(63) == midi_note::Ds4);
  REQUIRE(midi_value_to_note(64) == midi_note::E4);
  REQUIRE(midi_value_to_note(65) == midi_note::F4);
  REQUIRE(midi_value_to_note(66) == midi_note::Fs4);
  REQUIRE(midi_value_to_note(67) == midi_note::G4);
  REQUIRE(midi_value_to_note(68) == midi_note::Gs4);
  REQUIRE(midi_value_to_note(69) == midi_note::A4);
  REQUIRE(midi_value_to_note(70) == midi_note::As4);
  REQUIRE(midi_value_to_note(71) == midi_note::B4);
  REQUIRE(midi_value_to_note(72) == midi_note::C5);
  REQUIRE(midi_value_to_note(73) == midi_note::Cs5);
  REQUIRE(midi_value_to_note(74) == midi_note::D5);
  REQUIRE(midi_value_to_note(75) == midi_note::Ds5);
  REQUIRE(midi_value_to_note(76) == midi_note::E5);
  REQUIRE(midi_value_to_note(77) == midi_note::F5);
  REQUIRE(midi_value_to_note(78) == midi_note::Fs5);
  REQUIRE(midi_value_to_note(79) == midi_note::G5);
  REQUIRE(midi_value_to_note(80) == midi_note::Gs5);
  REQUIRE(midi_value_to_note(81) == midi_note::A5);
  REQUIRE(midi_value_to_note(82) == midi_note::As5);
  REQUIRE(midi_value_to_note(83) == midi_note::B5);
  REQUIRE(midi_value_to_note(84) == midi_note::C6);
  REQUIRE(midi_value_to_note(85) == midi_note::Cs6);
  REQUIRE(midi_value_to_note(86) == midi_note::D6);
  REQUIRE(midi_value_to_note(87) == midi_note::Ds6);
  REQUIRE(midi_value_to_note(88) == midi_note::E6);
  REQUIRE(midi_value_to_note(89) == midi_note::F6);
  REQUIRE(midi_value_to_note(90) == midi_note::Fs6);
  REQUIRE(midi_value_to_note(91) == midi_note::G6);
  REQUIRE(midi_value_to_note(92) == midi_note::Gs6);
  REQUIRE(midi_value_to_note(93) == midi_note::A6);
  REQUIRE(midi_value_to_note(94) == midi_note::As6);
  REQUIRE(midi_value_to_note(95) == midi_note::B6);
  REQUIRE(midi_value_to_note(96) == midi_note::C7);
  REQUIRE(midi_value_to_note(97) == midi_note::Cs7);
  REQUIRE(midi_value_to_note(98) == midi_note::D7);
  REQUIRE(midi_value_to_note(99) == midi_note::Ds7);
  REQUIRE(midi_value_to_note(100) == midi_note::E7);
  REQUIRE(midi_value_to_note(101) == midi_note::F7);
  REQUIRE(midi_value_to_note(102) == midi_note::Fs7);
  REQUIRE(midi_value_to_note(103) == midi_note::G7);
  REQUIRE(midi_value_to_note(104) == midi_note::Gs7);
  REQUIRE(midi_value_to_note(105) == midi_note::A7);
  REQUIRE(midi_value_to_note(106) == midi_note::As7);
  REQUIRE(midi_value_to_note(107) == midi_note::B7);
  REQUIRE(midi_value_to_note(108) == midi_note::C8);
  REQUIRE(midi_value_to_note(109) == midi_note::Cs8);
  REQUIRE(midi_value_to_note(110) == midi_note::D8);
  REQUIRE(midi_value_to_note(111) == midi_note::Ds8);
  REQUIRE(midi_value_to_note(112) == midi_note::E8);
  REQUIRE(midi_value_to_note(113) == midi_note::F8);
  REQUIRE(midi_value_to_note(114) == midi_note::Fs8);
  REQUIRE(midi_value_to_note(115) == midi_note::G8);
  REQUIRE(midi_value_to_note(116) == midi_note::Gs8);
  REQUIRE(midi_value_to_note(117) == midi_note::A8);
  REQUIRE(midi_value_to_note(118) == midi_note::As8);
  REQUIRE(midi_value_to_note(119) == midi_note::B8);
  REQUIRE(midi_value_to_note(120) == midi_note::C9);
  REQUIRE(midi_value_to_note(121) == midi_note::Cs9);
  REQUIRE(midi_value_to_note(122) == midi_note::D9);
  REQUIRE(midi_value_to_note(123) == midi_note::Ds9);
  REQUIRE(midi_value_to_note(124) == midi_note::E9);
  REQUIRE(midi_value_to_note(125) == midi_note::F9);
  REQUIRE(midi_value_to_note(126) == midi_note::Fs9);
  REQUIRE(midi_value_to_note(127) == midi_note::G9);
}

TEST_CASE("MidiNoteValidity", "midi_note_test")
{
  // Invalid midi values
  REQUIRE(!is_valid_midi_value(0));
  REQUIRE(!is_valid_midi_value(20));
  REQUIRE(!is_valid_midi_value(128));
  REQUIRE(!is_valid_midi_value(255));

  // Valid midi values.
  REQUIRE(is_valid_midi_value(21));
  REQUIRE(is_valid_midi_value(22));
  REQUIRE(is_valid_midi_value(23));
  REQUIRE(is_valid_midi_value(24));
  REQUIRE(is_valid_midi_value(25));
  REQUIRE(is_valid_midi_value(26));
  REQUIRE(is_valid_midi_value(27));
  REQUIRE(is_valid_midi_value(28));
  REQUIRE(is_valid_midi_value(29));
  REQUIRE(is_valid_midi_value(30));
  REQUIRE(is_valid_midi_value(31));
  REQUIRE(is_valid_midi_value(32));
  REQUIRE(is_valid_midi_value(33));
  REQUIRE(is_valid_midi_value(34));
  REQUIRE(is_valid_midi_value(35));
  REQUIRE(is_valid_midi_value(36));
  REQUIRE(is_valid_midi_value(37));
  REQUIRE(is_valid_midi_value(38));
  REQUIRE(is_valid_midi_value(39));
  REQUIRE(is_valid_midi_value(40));
  REQUIRE(is_valid_midi_value(41));
  REQUIRE(is_valid_midi_value(42));
  REQUIRE(is_valid_midi_value(43));
  REQUIRE(is_valid_midi_value(44));
  REQUIRE(is_valid_midi_value(45));
  REQUIRE(is_valid_midi_value(46));
  REQUIRE(is_valid_midi_value(47));
  REQUIRE(is_valid_midi_value(48));
  REQUIRE(is_valid_midi_value(49));
  REQUIRE(is_valid_midi_value(50));
  REQUIRE(is_valid_midi_value(51));
  REQUIRE(is_valid_midi_value(52));
  REQUIRE(is_valid_midi_value(53));
  REQUIRE(is_valid_midi_value(54));
  REQUIRE(is_valid_midi_value(55));
  REQUIRE(is_valid_midi_value(56));
  REQUIRE(is_valid_midi_value(57));
  REQUIRE(is_valid_midi_value(58));
  REQUIRE(is_valid_midi_value(59));
  REQUIRE(is_valid_midi_value(60));
  REQUIRE(is_valid_midi_value(61));
  REQUIRE(is_valid_midi_value(62));
  REQUIRE(is_valid_midi_value(63));
  REQUIRE(is_valid_midi_value(64));
  REQUIRE(is_valid_midi_value(65));
  REQUIRE(is_valid_midi_value(66));
  REQUIRE(is_valid_midi_value(67));
  REQUIRE(is_valid_midi_value(68));
  REQUIRE(is_valid_midi_value(69));
  REQUIRE(is_valid_midi_value(70));
  REQUIRE(is_valid_midi_value(71));
  REQUIRE(is_valid_midi_value(72));
  REQUIRE(is_valid_midi_value(73));
  REQUIRE(is_valid_midi_value(74));
  REQUIRE(is_valid_midi_value(75));
  REQUIRE(is_valid_midi_value(76));
  REQUIRE(is_valid_midi_value(77));
  REQUIRE(is_valid_midi_value(78));
  REQUIRE(is_valid_midi_value(79));
  REQUIRE(is_valid_midi_value(80));
  REQUIRE(is_valid_midi_value(81));
  REQUIRE(is_valid_midi_value(82));
  REQUIRE(is_valid_midi_value(83));
  REQUIRE(is_valid_midi_value(84));
  REQUIRE(is_valid_midi_value(85));
  REQUIRE(is_valid_midi_value(86));
  REQUIRE(is_valid_midi_value(87));
  REQUIRE(is_valid_midi_value(88));
  REQUIRE(is_valid_midi_value(89));
  REQUIRE(is_valid_midi_value(90));
  REQUIRE(is_valid_midi_value(91));
  REQUIRE(is_valid_midi_value(92));
  REQUIRE(is_valid_midi_value(93));
  REQUIRE(is_valid_midi_value(94));
  REQUIRE(is_valid_midi_value(95));
  REQUIRE(is_valid_midi_value(96));
  REQUIRE(is_valid_midi_value(97));
  REQUIRE(is_valid_midi_value(98));
  REQUIRE(is_valid_midi_value(99));
  REQUIRE(is_valid_midi_value(100));
  REQUIRE(is_valid_midi_value(101));
  REQUIRE(is_valid_midi_value(102));
  REQUIRE(is_valid_midi_value(103));
  REQUIRE(is_valid_midi_value(104));
  REQUIRE(is_valid_midi_value(105));
  REQUIRE(is_valid_midi_value(106));
  REQUIRE(is_valid_midi_value(107));
  REQUIRE(is_valid_midi_value(108));
  REQUIRE(is_valid_midi_value(109));
  REQUIRE(is_valid_midi_value(110));
  REQUIRE(is_valid_midi_value(111));
  REQUIRE(is_valid_midi_value(112));
  REQUIRE(is_valid_midi_value(113));
  REQUIRE(is_valid_midi_value(114));
  REQUIRE(is_valid_midi_value(115));
  REQUIRE(is_valid_midi_value(116));
  REQUIRE(is_valid_midi_value(117));
  REQUIRE(is_valid_midi_value(118));
  REQUIRE(is_valid_midi_value(119));
  REQUIRE(is_valid_midi_value(120));
  REQUIRE(is_valid_midi_value(121));
  REQUIRE(is_valid_midi_value(122));
  REQUIRE(is_valid_midi_value(123));
  REQUIRE(is_valid_midi_value(124));
  REQUIRE(is_valid_midi_value(125));
  REQUIRE(is_valid_midi_value(126));
  REQUIRE(is_valid_midi_value(127));
}

TEST_CASE("RemoveOctaveTest", "midi_note_test")
{
  REQUIRE(0 == get_octave(midi_note::A0));
  REQUIRE(0 == get_octave(midi_note::As0));
  REQUIRE(0 == get_octave(midi_note::B0));

  REQUIRE(1 == get_octave(midi_note::C1));
  REQUIRE(1 == get_octave(midi_note::Cs1));
  REQUIRE(1 == get_octave(midi_note::D1));
  REQUIRE(1 == get_octave(midi_note::Ds1));
  REQUIRE(1 == get_octave(midi_note::E1));
  REQUIRE(1 == get_octave(midi_note::F1));
  REQUIRE(1 == get_octave(midi_note::Fs1));
  REQUIRE(1 == get_octave(midi_note::G1));
  REQUIRE(1 == get_octave(midi_note::Gs1));
  REQUIRE(1 == get_octave(midi_note::A1));
  REQUIRE(1 == get_octave(midi_note::As1));
  REQUIRE(1 == get_octave(midi_note::B1));

  REQUIRE(2 == get_octave(midi_note::C2));
  REQUIRE(2 == get_octave(midi_note::Cs2));
  REQUIRE(2 == get_octave(midi_note::D2));
  REQUIRE(2 == get_octave(midi_note::Ds2));
  REQUIRE(2 == get_octave(midi_note::E2));
  REQUIRE(2 == get_octave(midi_note::F2));
  REQUIRE(2 == get_octave(midi_note::Fs2));
  REQUIRE(2 == get_octave(midi_note::G2));
  REQUIRE(2 == get_octave(midi_note::Gs2));
  REQUIRE(2 == get_octave(midi_note::A2));
  REQUIRE(2 == get_octave(midi_note::As2));
  REQUIRE(2 == get_octave(midi_note::B2));

  REQUIRE(3 == get_octave(midi_note::C3));
  REQUIRE(3 == get_octave(midi_note::Cs3));
  REQUIRE(3 == get_octave(midi_note::D3));
  REQUIRE(3 == get_octave(midi_note::Ds3));
  REQUIRE(3 == get_octave(midi_note::E3));
  REQUIRE(3 == get_octave(midi_note::F3));
  REQUIRE(3 == get_octave(midi_note::Fs3));
  REQUIRE(3 == get_octave(midi_note::G3));
  REQUIRE(3 == get_octave(midi_note::Gs3));
  REQUIRE(3 == get_octave(midi_note::A3));
  REQUIRE(3 == get_octave(midi_note::As3));
  REQUIRE(3 == get_octave(midi_note::B3));

  REQUIRE(4 == get_octave(midi_note::C4));
  REQUIRE(4 == get_octave(midi_note::Cs4));
  REQUIRE(4 == get_octave(midi_note::D4));
  REQUIRE(4 == get_octave(midi_note::Ds4));
  REQUIRE(4 == get_octave(midi_note::E4));
  REQUIRE(4 == get_octave(midi_note::F4));
  REQUIRE(4 == get_octave(midi_note::Fs4));
  REQUIRE(4 == get_octave(midi_note::G4));
  REQUIRE(4 == get_octave(midi_note::Gs4));
  REQUIRE(4 == get_octave(midi_note::A4));
  REQUIRE(4 == get_octave(midi_note::As4));
  REQUIRE(4 == get_octave(midi_note::B4));

  REQUIRE(5 == get_octave(midi_note::C5));
  REQUIRE(5 == get_octave(midi_note::Cs5));
  REQUIRE(5 == get_octave(midi_note::D5));
  REQUIRE(5 == get_octave(midi_note::Ds5));
  REQUIRE(5 == get_octave(midi_note::E5));
  REQUIRE(5 == get_octave(midi_note::F5));
  REQUIRE(5 == get_octave(midi_note::Fs5));
  REQUIRE(5 == get_octave(midi_note::G5));
  REQUIRE(5 == get_octave(midi_note::Gs5));
  REQUIRE(5 == get_octave(midi_note::A5));
  REQUIRE(5 == get_octave(midi_note::As5));
  REQUIRE(5 == get_octave(midi_note::B5));

  REQUIRE(6 == get_octave(midi_note::C6));
  REQUIRE(6 == get_octave(midi_note::Cs6));
  REQUIRE(6 == get_octave(midi_note::D6));
  REQUIRE(6 == get_octave(midi_note::Ds6));
  REQUIRE(6 == get_octave(midi_note::E6));
  REQUIRE(6 == get_octave(midi_note::F6));
  REQUIRE(6 == get_octave(midi_note::Fs6));
  REQUIRE(6 == get_octave(midi_note::G6));
  REQUIRE(6 == get_octave(midi_note::Gs6));
  REQUIRE(6 == get_octave(midi_note::A6));
  REQUIRE(6 == get_octave(midi_note::As6));
  REQUIRE(6 == get_octave(midi_note::B6));

  REQUIRE(7 == get_octave(midi_note::C7));
  REQUIRE(7 == get_octave(midi_note::Cs7));
  REQUIRE(7 == get_octave(midi_note::D7));
  REQUIRE(7 == get_octave(midi_note::Ds7));
  REQUIRE(7 == get_octave(midi_note::E7));
  REQUIRE(7 == get_octave(midi_note::F7));
  REQUIRE(7 == get_octave(midi_note::Fs7));
  REQUIRE(7 == get_octave(midi_note::G7));
  REQUIRE(7 == get_octave(midi_note::Gs7));
  REQUIRE(7 == get_octave(midi_note::A7));
  REQUIRE(7 == get_octave(midi_note::As7));
  REQUIRE(7 == get_octave(midi_note::B7));

  REQUIRE(8 == get_octave(midi_note::C8));
  REQUIRE(8 == get_octave(midi_note::Cs8));
  REQUIRE(8 == get_octave(midi_note::D8));
  REQUIRE(8 == get_octave(midi_note::Ds8));
  REQUIRE(8 == get_octave(midi_note::E8));
  REQUIRE(8 == get_octave(midi_note::F8));
  REQUIRE(8 == get_octave(midi_note::Fs8));
  REQUIRE(8 == get_octave(midi_note::G8));
  REQUIRE(8 == get_octave(midi_note::Gs8));
  REQUIRE(8 == get_octave(midi_note::A8));
  REQUIRE(8 == get_octave(midi_note::As8));
  REQUIRE(8 == get_octave(midi_note::B8));

  REQUIRE(9 == get_octave(midi_note::C9));
  REQUIRE(9 == get_octave(midi_note::Cs9));
  REQUIRE(9 == get_octave(midi_note::D9));
  REQUIRE(9 == get_octave(midi_note::Ds9));
  REQUIRE(9 == get_octave(midi_note::E9));
  REQUIRE(9 == get_octave(midi_note::F9));
  REQUIRE(9 == get_octave(midi_note::Fs9));
  REQUIRE(9 == get_octave(midi_note::G9));
}

TEST_CASE("GetOctaveTest", "midi_note_test")
{
  REQUIRE(note::A  == remove_octave(midi_note::A0));
  REQUIRE(note::As == remove_octave(midi_note::As0));
  REQUIRE(note::B  == remove_octave(midi_note::B0));

  REQUIRE(note::C  == remove_octave(midi_note::C2));
  REQUIRE(note::Cs == remove_octave(midi_note::Cs1));
  REQUIRE(note::D  == remove_octave(midi_note::D1));
  REQUIRE(note::Ds == remove_octave(midi_note::Ds1));
  REQUIRE(note::E  == remove_octave(midi_note::E1));
  REQUIRE(note::F  == remove_octave(midi_note::F1));
  REQUIRE(note::Fs == remove_octave(midi_note::Fs1));
  REQUIRE(note::G  == remove_octave(midi_note::G1));
  REQUIRE(note::Gs == remove_octave(midi_note::Gs1));
  REQUIRE(note::A  == remove_octave(midi_note::A1));
  REQUIRE(note::As == remove_octave(midi_note::As1));
  REQUIRE(note::B  == remove_octave(midi_note::B1));

  REQUIRE(note::C  == remove_octave(midi_note::C2));
  REQUIRE(note::Cs == remove_octave(midi_note::Cs2));
  REQUIRE(note::D  == remove_octave(midi_note::D2));
  REQUIRE(note::Ds == remove_octave(midi_note::Ds2));
  REQUIRE(note::E  == remove_octave(midi_note::E2));
  REQUIRE(note::F  == remove_octave(midi_note::F2));
  REQUIRE(note::Fs == remove_octave(midi_note::Fs2));
  REQUIRE(note::G  == remove_octave(midi_note::G2));
  REQUIRE(note::Gs == remove_octave(midi_note::Gs2));
  REQUIRE(note::A  == remove_octave(midi_note::A2));
  REQUIRE(note::As == remove_octave(midi_note::As2));
  REQUIRE(note::B  == remove_octave(midi_note::B2));

  REQUIRE(note::C  == remove_octave(midi_note::C3));
  REQUIRE(note::Cs == remove_octave(midi_note::Cs3));
  REQUIRE(note::D  == remove_octave(midi_note::D3));
  REQUIRE(note::Ds == remove_octave(midi_note::Ds3));
  REQUIRE(note::E  == remove_octave(midi_note::E3));
  REQUIRE(note::F  == remove_octave(midi_note::F3));
  REQUIRE(note::Fs == remove_octave(midi_note::Fs3));
  REQUIRE(note::G  == remove_octave(midi_note::G3));
  REQUIRE(note::Gs == remove_octave(midi_note::Gs3));
  REQUIRE(note::A  == remove_octave(midi_note::A3));
  REQUIRE(note::As == remove_octave(midi_note::As3));
  REQUIRE(note::B  == remove_octave(midi_note::B3));

  REQUIRE(note::C  == remove_octave(midi_note::C4));
  REQUIRE(note::Cs == remove_octave(midi_note::Cs4));
  REQUIRE(note::D  == remove_octave(midi_note::D4));
  REQUIRE(note::Ds == remove_octave(midi_note::Ds4));
  REQUIRE(note::E  == remove_octave(midi_note::E4));
  REQUIRE(note::F  == remove_octave(midi_note::F4));
  REQUIRE(note::Fs == remove_octave(midi_note::Fs4));
  REQUIRE(note::G  == remove_octave(midi_note::G4));
  REQUIRE(note::Gs == remove_octave(midi_note::Gs4));
  REQUIRE(note::A  == remove_octave(midi_note::A4));
  REQUIRE(note::As == remove_octave(midi_note::As4));
  REQUIRE(note::B  == remove_octave(midi_note::B4));

  REQUIRE(note::C  == remove_octave(midi_note::C5));
  REQUIRE(note::Cs == remove_octave(midi_note::Cs5));
  REQUIRE(note::D  == remove_octave(midi_note::D5));
  REQUIRE(note::Ds == remove_octave(midi_note::Ds5));
  REQUIRE(note::E  == remove_octave(midi_note::E5));
  REQUIRE(note::F  == remove_octave(midi_note::F5));
  REQUIRE(note::Fs == remove_octave(midi_note::Fs5));
  REQUIRE(note::G  == remove_octave(midi_note::G5));
  REQUIRE(note::Gs == remove_octave(midi_note::Gs5));
  REQUIRE(note::A  == remove_octave(midi_note::A5));
  REQUIRE(note::As == remove_octave(midi_note::As5));
  REQUIRE(note::B  == remove_octave(midi_note::B5));

  REQUIRE(note::C  == remove_octave(midi_note::C6));
  REQUIRE(note::Cs == remove_octave(midi_note::Cs6));
  REQUIRE(note::D  == remove_octave(midi_note::D6));
  REQUIRE(note::Ds == remove_octave(midi_note::Ds6));
  REQUIRE(note::E  == remove_octave(midi_note::E6));
  REQUIRE(note::F  == remove_octave(midi_note::F6));
  REQUIRE(note::Fs == remove_octave(midi_note::Fs6));
  REQUIRE(note::G  == remove_octave(midi_note::G6));
  REQUIRE(note::Gs == remove_octave(midi_note::Gs6));
  REQUIRE(note::A  == remove_octave(midi_note::A6));
  REQUIRE(note::As == remove_octave(midi_note::As6));
  REQUIRE(note::B  == remove_octave(midi_note::B6));

  REQUIRE(note::C  == remove_octave(midi_note::C7));
  REQUIRE(note::Cs == remove_octave(midi_note::Cs7));
  REQUIRE(note::D  == remove_octave(midi_note::D7));
  REQUIRE(note::Ds == remove_octave(midi_note::Ds7));
  REQUIRE(note::E  == remove_octave(midi_note::E7));
  REQUIRE(note::F  == remove_octave(midi_note::F7));
  REQUIRE(note::Fs == remove_octave(midi_note::Fs7));
  REQUIRE(note::G  == remove_octave(midi_note::G7));
  REQUIRE(note::Gs == remove_octave(midi_note::Gs7));
  REQUIRE(note::A  == remove_octave(midi_note::A7));
  REQUIRE(note::As == remove_octave(midi_note::As7));
  REQUIRE(note::B  == remove_octave(midi_note::B7));

  REQUIRE(note::C  == remove_octave(midi_note::C8));
  REQUIRE(note::Cs == remove_octave(midi_note::Cs8));
  REQUIRE(note::D  == remove_octave(midi_note::D8));
  REQUIRE(note::Ds == remove_octave(midi_note::Ds8));
  REQUIRE(note::E  == remove_octave(midi_note::E8));
  REQUIRE(note::F  == remove_octave(midi_note::F8));
  REQUIRE(note::Fs == remove_octave(midi_note::Fs8));
  REQUIRE(note::G  == remove_octave(midi_note::G8));
  REQUIRE(note::Gs == remove_octave(midi_note::Gs8));
  REQUIRE(note::A  == remove_octave(midi_note::A8));
  REQUIRE(note::As == remove_octave(midi_note::As8));
  REQUIRE(note::B  == remove_octave(midi_note::B8));

  REQUIRE(note::C  == remove_octave(midi_note::C9));
  REQUIRE(note::Cs == remove_octave(midi_note::Cs9));
  REQUIRE(note::D  == remove_octave(midi_note::D9));
  REQUIRE(note::Ds == remove_octave(midi_note::Ds9));
  REQUIRE(note::E  == remove_octave(midi_note::E9));
  REQUIRE(note::F  == remove_octave(midi_note::F9));
  REQUIRE(note::Fs == remove_octave(midi_note::Fs9));
  REQUIRE(note::G  == remove_octave(midi_note::G9));
}